### ISSUE TITLE
Question: Is it possible to run it?

### ISSUE THREAD

**Issue by Aspector1** [Martyn0324/Hakisa#1]

**Comment by Martyn0324** [comment]
**Exploration Mode:**

https://user-images.githubusercontent.com/28028007/198142221-2bc41846-3d68-412c-839b-8be67c8eb23e.mp4


https://user-images.githubusercontent.com/28028007/198151996-b50adf85-354d-41ab-b6b6-c27724e1fca3.mp4


Delay between each action:

![image](https://user-images.githubusercontent.com/28028007/198152052-0f091bfd-ab2f-4b39-b96f-1fb1967072ba.png)


**Study Mode:**

![image](https://user-images.githubusercontent.com/28028007/198152201-6265ace5-6aff-47aa-9c05-5750bb18e7a0.png)


Currently I can't say anything about Play Mode, as I've passed these times just checking if everything's ok and making small modifications(which still haven't been included into the Notebook, but will be soon, with a sample code for playing Jigoku and Bullet Heaven)

**EDIT: Currently, Play Mode isn't effectively functional, as I've said in the Read Me. I'm making some experiments and trying to make something that really works**

**Comment by Aspector1** [comment]
![image](https://user-images.githubusercontent.com/84536195/198843515-929b8c39-c562-4c66-8d8f-69ff03ad0a14.png)

**Comment by Martyn0324** [comment]
Oh, sorry. I forgot to fix that in the GitHub notebook. That was a function I was testing, but in the end I ended up removing it. Just remove that argument and it should run fine.

I'll see if I upload a new jupyter notebook soon, as I'm currently testing if I can replace PyAutoGUI by the keyboard and mouse modules completely. Some games don't work with PyAutoGUI, but work with keyboard and mouse modules. I don't know if the inverse also happens

**Comment by Aspector1** [comment]
> Oh, sorry. I forgot to fix that in the GitHub notebook. That was a function I was testing, but in the end I ended up removing it. Just remove that argument and it should run fine.
> 
> I'll see if I update a new jupyter notebook soon, as I'm currently testing if I can replace PyAutoGUI by the keyboard and mouse modules completely. Some games don't work with PyAutoGUI, but work with keyboard and mouse modules. I don't know if the inverse also happens

Thanks

**Comment by Aspector1** [comment]
![image](https://user-images.githubusercontent.com/84536195/198844124-ba6edf52-9979-49e4-a5b2-479564e5eefe.png)
So you haven't found a solution to this problem?

**Comment by Martyn0324** [comment]
Strange...I didn't get this problem. That function should extract floats(the command values) from memory, so there should be no problem. Did you make sure to pass the arguments into `create_memory` in the right order?

**Comment by Aspector1** [comment]
> Strange...I didn't get this problem. That function should extract floats(the command values) from memory, so there should be no problem. Did you make sure to pass the arguments into `create_memory` in the right order?

I didn't change anything in your code and just tried to run the study, but it didn't work.

**Comment by Martyn0324** [comment]
> > Strange...I didn't get this problem. That function should extract floats(the command values) from memory, so there should be no problem. Did you make sure to pass the arguments into `create_memory` in the right order?
> 
> I didn't change anything in your code and just tried to run the study, but it didn't work.

Did you have any values defined as labels in the same format as they're saved in memory?

**Comment by Martyn0324** [comment]
> ![image](https://user-images.githubusercontent.com/84536195/198844124-ba6edf52-9979-49e4-a5b2-479564e5eefe.png) So you haven't found a solution to this problem?

I think I know the problem now. The way the memory will be mounted now makes labels have `[(action_type, actions1, actions2)]` with `action_type.size() = [1]` and actions1 and 2 having size `[1, 1]`, which, in `np.stack()` , generates an np.array of dtype `object`

I'll see how I can fix this.

**Comment by Martyn0324** [comment]
> > Strange...I didn't get this problem. That function should extract floats(the command values) from memory, so there should be no problem. Did you make sure to pass the arguments into `create_memory` in the right order?
> 
> I didn't change anything in your code and just tried to run the study, but it didn't work.

I think I know what is happening now. Since `action_type` has size `[1]` while actions 1 and 2 have size `[1, 1]`, `np.stack()` will return an array of type `object`, which isn't supported by `torch.from_numpy()`.

I don't get this error in my machine with `torch.__version__ == 1.12`, but in a cloud server with version 1.11, I do get this error.

I'll add a function `astype(float)` to `np.stack()`(since we already convert the data to float after getting a tensor). I hope this won't compromise the data at all.
