### ISSUE TITLE
List index out of range error when running Exploration Loop

### ISSUE THREAD

**Issue by AidyTheWeird** [Martyn0324/Hakisa#2]
![image](https://user-images.githubusercontent.com/35501029/201384318-3f6f5c1a-c668-4a72-a6fe-25f9ea9a0e92.png)

**Comment by Martyn0324** [comment]
Oh, my bad... The problem is actually in Hakisa's code:

```py
    def forward(self, input=None, frame_sequence=None, previous_action=None, previous_reward=None):

        if self.mode == "Explore":
            # Reinventing the wheel didn't work. Now, in exploration mode, Hakisa will simply generate random numbers.

            if self.n_command_types > 1:
                command_type = torch.randint(0, self.n_command_types, size=(1,), device=device)
            else:
                command_type = torch.ones((0), device=device)
                
            action1 = torch.normal(0, max(dataset.actions1.values()), size=(1, 1), device=device)
            action2 = torch.normal(0, max(dataset.actions2.values()), size=(1, 1), device=device)

            return (command_type, action1, action2)

```

`command_type = torch.ones((0), device=device)` will actually generate a torch tensor that is literally `([])`

The correct form should be `command_type = torch.zeros((1), device=device)` which will generate `([0.])`

It should work now.

**Comment by AidyTheWeird** [comment]
![image](https://user-images.githubusercontent.com/35501029/201470692-df6ec514-8d3e-4f23-9156-56af8c03c616.png)
I get this error now

**Comment by Martyn0324** [comment]
Ops². Replace `long()` by `astype(int)`. I thought cmd_type was still a tensor.

I'll fix it

**Comment by AidyTheWeird** [comment]
yeah tried fixing it myself by replacing `long()` with `int()`, but no luck. `astype(int)` appears to cause list index out of range error again

**Comment by Martyn0324** [comment]
Strange...cmd_type has a single dimension and it's a float32. It'll be a `tensor([0.])`. The input for the `get_command` function will be `[0.]`, a numpy array, and `astype(int)` should simply convert it to `[0]`.

I don't quite get it why this will cause a list index out of range

**Comment by AidyTheWeird** [comment]
I tried setting a break point (no idea what I'm doing tbh) at `if cmd_type.ndim > 1:` and it shows `cmd_type: array([1], dtype=int64)`  idk if that's any help, you can let me know if you need anything from my side

**Comment by Martyn0324** [comment]
Hm... Are you using the new notebook I uploaded yesterday? Try checking Hakisa's `forward` function:

```py

def forward(self, input=None, frame_sequence=None, previous_action=None, previous_reward=None):

        if self.mode == "Explore":
            # Reinventing the wheel didn't work. Now, in exploration mode, Hakisa will simply generate random numbers.

            if self.n_command_types > 1:
                command_type = torch.randint(0, self.n_command_types, size=(1,), device=device) # Outputting a vector.
            else:
                command_type = torch.zeros((1), device=device)
                
            action1 = torch.normal(0, max(dataset.actions1.values()), size=(1, 1), device=device)
            action2 = torch.normal(0, max(dataset.actions2.values()), size=(1, 1), device=device)

            return (command_type, action1, action2)
```

Attention to `command_type = torch.zeros((1), device=device)`. In the first version of the jupyter notebook, I made a mistake here and instead of using `zeros` I've used `torch.ones`, which generates a `tensor([1.])` instead of `tensor([0.])`. Using 0 makes more sense, considering that this tensor will be used as index for a list.

**Comment by AidyTheWeird** [comment]
Yeah, using the latest version, the one with `torch.zeros((1), device=device)`

**Comment by Martyn0324** [comment]
What code are you using for your breakpoint? Can you post it here?

**Comment by AidyTheWeird** [comment]
not sure what you mean, this is what I've got

![image](https://user-images.githubusercontent.com/35501029/201485079-638d7a1e-e63e-4338-b514-583a9f9246d9.png)

**Comment by Martyn0324** [comment]
Oh, I get it now... You're using Hakisa for Jigoku Kisetsukan, right? When calling Hakisa, did you correctly specified `n_command_types=0` or maybe `n_command_types=1`?

If you're using `hakisa = Hakisa(n_command_types=3, mode='Explore').to(device)`, then it won't work. `n_command_types=3` is what I was using for Bullet Heaven 2(which has 3 command types, move, click and rightclick)

Also, I'll change another thing in the code regarding this replacement from `torch.ones` to `torch.zeros`

**Comment by AidyTheWeird** [comment]
ahhhhhh yes that's right, I changed it to `n_command_types=1` now and It works.
