### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by nyaumii** [Martyn0324/Hakisa#3]
![image](https://user-images.githubusercontent.com/79224797/205472582-1e2d3572-d00c-482e-bb3c-1525bebac7aa.png)

I'm really new to this and I'm wondering if I'm doing something wrong.

**Comment by Martyn0324** [comment]
Yes, you have to install those libraries(preferably with `pip install`). Numpy, mss, matplotlib, torch(with cuda), PIL, scikit-learn, keyboard, mouse, and pytesseract.
time, WinSound and re are already included in Python.
